# Usa a imagem oficial do Node 24 (LTS) como base
FROM node:24-alpine

# Define a pasta de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependências primeiro (otimiza o cache do Docker)
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copia todo o restante do código do backend para o container
COPY . .

# Gera o Prisma Client dentro do container para garantir as tipagens
RUN npx prisma generate

# Expõe a porta 3000 que o seu servidor usa
EXPOSE 3000

# Comando para rodar o app em modo de desenvolvimento
CMD ["npm", "run", "dev"]